name: PR-Check

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  BUILD_TYPE: Release
  PICO_SDK_PATH: ${{github.workspace}}/.pico-sdk

jobs:
  build:
    uses: ./.github/workflows/build_base.yml
    with:
      upload_artifacts: false